# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'StateMonitoringDemo' do
  use_frameworks!

  # Pods for StateMonitoringDemo
	pod 'SwiftMessages'

end
